const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.DragnDrop.Cnds.OnDrop
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{子弹: 0},
	{bullet: 0},
	{淡入淡出: 0},
	{explosion: 0},
	{health: 0},
	{big: 0},
	{wait: 0},
	{monster: 0},
	{run: 0},
	{攻擊力: 0},
	{防禦力: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{边界限制: 0},
	{player: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{score: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Text: 0},
	{任務: 0},
	{GAMEOVER: 0},
	{joystickB: 0},
	{拖放: 0},
	{joystickS: 0},
	{Sprite4: 0},
	{Touch: 0},
	{timed: 0},
	{touchx: 0},
	{touchy: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	bullet: class extends self.ISpriteInstance {},
	explosion: class extends self.ISpriteInstance {},
	monster: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	score: class extends self.ITextInstance {},
	health: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	任務: class extends self.ITextInstance {},
	GAMEOVER: class extends self.ITextInstance {},
	joystickB: class extends self.ISpriteInstance {},
	joystickS: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {}
}