const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Plugins.Touch.Exps.AccelerationX,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Plugins.Touch.Exps.AccelerationY
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{子弹: 0},
	{bullet: 0},
	{淡入淡出: 0},
	{explosion: 0},
	{health: 0},
	{monster: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{边界限制: 0},
	{player: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Text: 0},
	{Text2: 0},
	{Touch: 0},
	{score: 0},
	{mose1: 0},
	{mose2: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	bullet: class extends self.ISpriteInstance {},
	explosion: class extends self.ISpriteInstance {},
	monster: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {}
}